language: ruby
rvm:
  - 2.4.0
test:
  adapter: postgresql
  database: travis_ci_test
script:
  - RAILS_ENV=test bundle exec spring rake test
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec spring rake db:create
  - RAILS_ENV=test bundle exec spring rake db:migrate
